# Use a random port
server.port: 0
spring.application.name: zookeeper-sandbox

# Enable Zookeeper
spring.cloud.zookeeper.discovery.enabled: true
spring.cloud.zookeeper.enabled: true

# Disable Eureka         
ribbon.eureka.enabled: false
eureka.client.enabled: false          

# Logging:      
logging.level:
#   com.netflix: TRACE
  org.springframework: DEBUG